### ISSUE TITLE
Combination rule

### ISSUE THREAD

**Issue by ajkluber** [ajkluber/model_builder#1]
So should we change the default combination rule to "2" to handle beads with different radii?

https://github.com/ajkluber/model_builder/blob/master/models/CoarseGrainedModel.py#L419-L422

**Comment by TensorDuck** [comment]
I agree that would be best.

**Comment by ajkluber** [comment]
Hold up. I hadn't checked the gromacs manual thoroughly enough. Rule 2 doesn't work because it automatically sets the attraction term as well. We have to use rule 1 then.

See section 4.1.1
[Gromacs_Manual.pdf](https://github.com/ajkluber/model_builder/files/8074/Gromacs_Manual.pdf)

**Comment by TensorDuck** [comment]
Oh, my bad. I confused the rules in my head. I think we should keep rule 1 and just double all the lengths. That would work reasonably well considering most of the beads are almost the same size anyways.

**Comment by TensorDuck** [comment]
I've been going over the Cheung and Onuchic 2003 paper again. I noticed that they also have a factor of 0.7 in their repulsive interactions. So for a Ca-Ca interaction, they used a radii of 1.9A for each, and that lead to the excluded volume term being 2.66A, not 0.4A like we've been using. I found that if we use a 0.4A interaction term for repulsion, it actually leads to the proteins "blowing up" very easily. 

Consequently, us using half radius inadvertently actually improved matters. 

They also used the flavored radii in order to account for sterics better. I don't think it would make a big difference with additive versus multiplicative. But, I was thinking if you wanted to implement the additive term, we can always input a paired interaction into the .top file as a r12 interaction under the pairtypes. I think we can input using func 1 (r12-r6), and just set r6 =0, and compute the r12 manually each time. it will be extra overhead in writing the files but likely won't affect the simulation time as much. I can see about implementing some of this and I'll let you know.

**Comment by TensorDuck** [comment]
for reference, fixed atomic sizes in [dd9ba39ed0bdcae1b7e2aa6b93054c5b098802fc](https://github.com/ajkluber/model_builder/commit/dd9ba39ed0bdcae1b7e2aa6b93054c5b098802fc)

**Comment by ajkluber** [comment]
Thanks for this Justin. Following Cheung, et.al. 2003 sounds like the best way to go for the time being, so I will close this issue. I will leave the discussion of robustly testing the CACB model to a future date. Thanks for figuring this out!
